app/models/entities/__init__.py
# app/models/entities/__init__.py
from .user import User
from .client import Client
from .robot_model import RobotModel
from .software import Software
from .group import Group
from .role import Role
from .robot_instance import RobotInstance
from .software_version import SoftwareVersion

__all__ = [
    'User',
    'Client',
    'RobotModel', 
    'Software',
    'Group',
    'Role',
    'RobotInstance',
    'SoftwareVersion'
]

app/routes/additional_params.py
#app/routes/additional_params.py

from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from app.models.entities import Client, RobotInstance, RobotModel, Software, SoftwareVersion
from app.models.parameters.definitions import ParameterDefinition
from app.models.parameters.values import ParameterValue
from app.models.enums import EntityType
from app.extensions import db
from sqlalchemy.exc import SQLAlchemyError

additional_params_bp = Blueprint('additional_params', __name__, url_prefix='/additional-params')

def get_entity_by_table_name(table_name, table_id=None, entity_name=None):
    entity_mappings = {
        'client': Client,
        'robot_instance': RobotInstance,
        'robot_model': RobotModel,
        'software': Software,
        'software_version': SoftwareVersion
    }
    
    EntityClass = entity_mappings.get(table_name.lower().rstrip('s'))
    if not EntityClass:
        abort(404, f"Type d'entité inconnu: {table_name}")
    
    if entity_name:
        entity = EntityClass.query.filter_by(name=entity_name).first_or_404()
    else:
        entity = EntityClass.query.get_or_404(table_id)
    
    return entity, EntityClass.__tablename__



# Fonction utilitaire pour obtenir le nom d'affichage de l'entité
def get_entity_display_name(entity, table_name):
    if table_name == 'clients':
        return entity.name
    elif table_name == 'robot_clients':
        return f"Robot {entity.serial_number} - {entity.client.name}"
    elif table_name == 'robot_models':
        return entity.name
    elif table_name == 'software':
        return entity.name
    elif table_name == 'software_versions':
        return f"{entity.software.name} v{entity.version}"
    else:
        return f"Entité #{entity.id}"

# ======== ROUTES D'AFFICHAGE ========

@additional_params_bp.route('/view/<string:table_name>/<string:entity_identifier>')
def view_additional_params(table_name, entity_identifier):
    entity, actual_table_name = get_entity_by_table_name(table_name, entity_name=entity_identifier)
    entity_name = get_entity_display_name(entity, actual_table_name)
    
    parameter_definitions = ParameterDefinition.query.filter_by(target_entity=entity.entity_type).all()
    parameter_values = ParameterValue.query.filter_by(
        entity_id=entity.id,
        entity_type=entity.entity_type
    ).all()
    
    return render_template(
        'view/additional_params.html',
        entity=entity,
        entity_name=entity_name,
        table_name=actual_table_name,
        parameter_definitions=parameter_definitions,
        parameter_values=parameter_values
    )


@additional_params_bp.route('/list')
def list_additional_params():
    """Liste toutes les configurations de paramètres additionnels"""
    configs = ParameterDefinition.query.all()
    
    # Enrichir les configurations avec des informations supplémentaires
    for config in configs:
        config.param_count = ParameterValue.query.filter_by(
            additional_parameters_config_id=config.id
        ).count()
        
        try:
            entity, actual_table_name = get_entity_by_table_name(config.table_name, table_id=config.table_id)
            config.entity_name = get_entity_display_name(entity, actual_table_name)
        except:
            config.entity_name = f"Entité inconnue ({config.table_name} #{config.table_id})"
    
    return render_template(
        'list/additional_params.html',
        configs=configs
    )

# ======== ROUTES D'ÉDITION ========

@additional_params_bp.route('/edit/<string:table_name>/<string:entity_identifier>', methods=['GET', 'POST'])
def edit_additional_params(table_name, entity_identifier):
    entity, actual_table_name = get_entity_by_table_name(table_name, entity_name=entity_identifier)
    entity_name = entity.name
    
    if request.method == 'POST':
        try:
            for key, value in request.form.items():
                if key.startswith('param_'):
                    param_id = int(key.split('_')[1])
                    param_value = ParameterValue.query.get(param_id)
                    if param_value:
                        param_value.value = value
                    else:
                        new_param = ParameterValue(
                            parameter_definition_id=param_id,
                            entity_id=entity.id,
                            entity_type=entity.entity_type,
                            value=value
                        )
                        db.session.add(new_param)
            
            db.session.commit()
            flash('Paramètres mis à jour avec succès', 'success')
            return redirect(url_for('additional_params.view_additional_params', table_name=table_name, entity_identifier=entity_identifier))
        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f'Erreur lors de la mise à jour des paramètres : {str(e)}', 'danger')
    
    parameter_definitions = ParameterDefinition.query.filter_by(target_entity=entity.entity_type).all()
    parameter_values = ParameterValue.query.filter_by(entity_id=entity.id, entity_type=entity.entity_type).all()
    
    return render_template(
        'edit/additional_params.html',
        entity=entity,
        entity_name=entity_name,
        table_name=actual_table_name,
        parameter_definitions=parameter_definitions,
        parameter_values=parameter_values
    )


@additional_params_bp.route('/add/<string:table_name>/<string:entity_identifier>', methods=['GET', 'POST'])
def add_additional_param(table_name, entity_identifier):
    entity, actual_table_name = get_entity_by_table_name(table_name, entity_name=entity_identifier)
    
    if request.method == 'POST':
        name = request.form.get('name')
        param_type = request.form.get('type')
        
        if not name or not param_type:
            flash("Le nom et le type du paramètre sont obligatoires.", "error")
            return redirect(url_for('additional_params.add_additional_param', table_name=table_name, entity_identifier=entity_identifier))
        
        try:
            # Créer la nouvelle définition de paramètre
            new_definition = ParameterDefinition(
                name=name,
                target_entity=entity.entity_type,
                type=param_type
            )
            db.session.add(new_definition)
            db.session.flush()
            
            # Créer la nouvelle valeur de paramètre
            value = request.form.get('value', '')
            if param_type == 'enum':
                enum_values = request.form.getlist('enum_values[]')
                value = ','.join(filter(None, enum_values))
            
            new_value = ParameterValue(
                parameter_definition_id=new_definition.id,
                entity_id=entity.id,
                entity_type=entity.entity_type,
                value=value
            )
            db.session.add(new_value)
            db.session.commit()
            
            flash(f"Paramètre '{name}' ajouté avec succès !", "success")
            return redirect(url_for('additional_params.view_additional_params', table_name=table_name, entity_identifier=entity_identifier))
            
        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f"Erreur lors de l'ajout du paramètre : {str(e)}", "error")
    
    return render_template(
        'add/additional_params.html',
        table_name=actual_table_name,
        entity_name=entity.name,
        entity=entity
    )


def get_additional_params_data(entity):
    """Récupère les données des paramètres additionnels pour une entité donnée"""
    parameter_definitions = ParameterDefinition.query.filter_by(target_entity=entity.entity_type).all()
    parameter_values = ParameterValue.query.filter_by(
        entity_id=entity.id,
        entity_type=entity.entity_type
    ).all()
    
    return {
        'parameter_definitions': parameter_definitions,
        'parameter_values': parameter_values,
        'has_params': len(parameter_values) > 0
    }

app/routes/configurations.py
# app/routes/configurations.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.models.configuration import ConfigurationInstance, ConfigSchema, ConfigFileParser
from app.models.entities import Client, Software, SoftwareVersion
from app.models.parameters import ParameterDefinition, ParameterValue
from app.models.enums import EntityType
from app.extensions import db
from sqlalchemy.exc import SQLAlchemyError

configurations_bp = Blueprint('configurations', __name__, url_prefix='/configurations')

@configurations_bp.route('/list')
def list():
    configurations = ConfigurationInstance.query.all()
    
    # Calcul des statistiques
    
    # Nombre de logiciels concernés
    # Nous comptons les logiciels distincts liés aux versions de logiciels utilisées
    # dans les configurations
    total_softwares = db.session.query(func.count(distinct(Software.id)))\
        .join(SoftwareVersion, SoftwareVersion.software_id == Software.id)\
        .join(ConfigurationInstance, ConfigurationInstance.software_version_id == SoftwareVersion.id)\
        .scalar()
    
    # Nombre de clients utilisant ces configurations
    total_clients = db.session.query(func.count(distinct(Client.id)))\
        .join(ClientConfiguration, ClientConfiguration.client_id == Client.id)\
        .join(ConfigurationInstance, ConfigurationInstance.id == ClientConfiguration.config_id)\
        .scalar()
    
    return render_template('list/configuration_instances.html', 
                          configurations=configurations,
                          total_softwares=total_softwares,
                          total_clients=total_clients)

@configurations_bp.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        try:
            file = request.files['config_file']
            entity_type = request.form['entity_type']
            entity_id = request.form['entity_id']
            
            # Créer une nouvelle instance de configuration
            new_config = ConfigurationInstance(
                entity_type=EntityType[entity_type.upper()],
                entity_id=entity_id,
                file_name=file.filename,
                raw_content=file.read().decode('utf-8')
            )
            
            db.session.add(new_config)
            db.session.flush()  # Pour obtenir l'ID de la nouvelle configuration
            
            # Parser le fichier et extraire les paramètres
            parser = ConfigFileParser(new_config)
            for name, value in parser.parse():
                definition = ParameterDefinition.query.filter_by(name=name).first()
                if not definition:
                    definition = new_config._create_definition(name, value)
                    db.session.add(definition)
                
                param_value = ParameterValue(
                    definition=definition,
                    value=value,
                    configuration_instance=new_config
                )
                db.session.add(param_value)
            
            db.session.commit()
            flash("Configuration ajoutée avec succès", "success")
            return redirect(url_for('configurations.list_configurations'))
        
        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f"Erreur lors de l'ajout de la configuration : {str(e)}", "error")
    
    entities = {
        'client': Client.query.all(),
        'software': Software.query.all(),
        'software_version': SoftwareVersion.query.all()
    }
    return render_template('add/configuration.html', entities=entities)

@configurations_bp.route('/view/<int:config_id>')
def view(config_id):
    config = ConfigurationInstance.query.get_or_404(config_id)
    return render_template('view/configuration.html', config=config)

@configurations_bp.route('/edit/<int:config_id>', methods=['GET', 'POST'])
def edit(config_id):
    config = ConfigurationInstance.query.get_or_404(config_id)
    if request.method == 'POST':
        try:
            # Mise à jour des paramètres existants
            for param in config.parameters:
                new_value = request.form.get(f'param_{param.id}')
                if new_value != param.value:
                    param.value = new_value
            
            db.session.commit()
            flash("Configuration mise à jour avec succès", "success")
            return redirect(url_for('configurations.view_configuration', config_id=config.id))
        
        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f"Erreur lors de la mise à jour : {str(e)}", "error")
    
    return render_template('edit/configuration.html', config=config)

@configurations_bp.route('/delete/<int:config_id>', methods=['POST'])
def delete(config_id):
    config = ConfigurationInstance.query.get_or_404(config_id)
    try:
        db.session.delete(config)
        db.session.commit()
        flash("Configuration supprimée avec succès", "success")
    except SQLAlchemyError as e:
        db.session.rollback()
        flash(f"Erreur lors de la suppression : {str(e)}", "error")
    return redirect(url_for('configurations.list_configurations'))

app/templates/macros/_entity.html
{# /templates/macros/_entity.html #}

{% macro parameters_section(configured_params, unconfigured_params, entity_type, entity_slug) %}
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">
            <i class="fas fa-cogs me-2"></i>Paramètres 
            <span class="badge bg-primary ms-2">{{ configured_params|length + unconfigured_params|length }}</span>
        </h5>
        {% if (configured_params|length + unconfigured_params|length) > 0 %}
        <a href="{{ url_for('additional_params_config.add', entity_type=entity_type, entity_slug=entity_slug) }}" class="btn btn-sm btn-primary">
            <i class="fas fa-plus me-1"></i>Ajouter un paramètre
        </a>
        {% endif %}
    </div>
    <div class="card-body">
        {% if (configured_params|length + unconfigured_params|length) > 0 %}
            {% from "macros/_table.html" import param_table %}
            {{ param_table(configured_params + unconfigured_params, entity_type, entity_slug, editable=true) }}
        {% else %}
        <div class="alert alert-info">
            <i class="fas fa-info-circle me-2"></i>Aucun paramètre défini.
            <a href="{{ url_for('additional_params_config.add', entity_type=entity_type, entity_slug=entity_slug) }}" class="alert-link">
                Ajouter un paramètre
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

{% macro configurations_section(configurations, entity_type, entity_id) %}
<div class="card mb-5">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">
            <i class="fas fa-file-code me-2"></i>Fichiers de configuration
            <span class="badge bg-primary ms-2">{{ configurations|length }}</span>
        </h5>
        {% if configurations|length > 0 %}
        <a href="{{ url_for('configurations.add', entity_type=entity_type, entity_id=entity_id) }}" class="btn btn-sm btn-primary">
            <i class="fas fa-plus me-1"></i>Ajouter une configuration
        </a>
        {% endif %}
    </div>
    <div class="card-body">
        {% if configurations|length > 0 %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered align-middle">
                <thead class="table-light">
                    <tr>
                        <th>Nom du fichier</th>
                        <th>Date</th>
                        <th>Logiciel</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for config in configurations %}
                    <tr>
                        <td>
                            {% if config.file_name %}
                                {{ config.file_name }}
                            {% else %}
                                Configuration #{{ config.id }}
                            {% endif %}
                        </td>
                        <td>{{ config.created_at|datetimeformat('%d/%m/%Y') }}</td>
                        <td>
                            {% if config.software_version %}
                                {{ config.software_version.software.name }} {{ config.software_version.version }}
                            {% else %}
                                Non spécifié
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{{ url_for('parsed_files.view', config_id=config.id) }}" class="btn btn-sm btn-info me-1">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ url_for('configurations.edit', config_id=config.id) }}" class="btn btn-sm btn-warning me-1">
                                <i class="fas fa-edit"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="alert alert-info">
            <i class="fas fa-info-circle me-2"></i>Aucune configuration enregistrée.
            <a href="{{ url_for('configurations.add', entity_type=entity_type, entity_id=entity_id) }}" class="alert-link">
                Ajouter une configuration
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

{% macro entity_header(entity, title_prefix="Détails de", title_field="name") %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">{{ title_prefix }} {{ entity[title_field] }}</h1>
    <div class="btn-group">
        {% if caller %}
            {{ caller() }}
        {% endif %}
    </div>
</div>
{% endmacro %}

{% macro standard_actions(entity, edit_url, entity_type, entity_slug) %}
<a href="{{ edit_url }}" class="btn btn-outline-primary">
    <i class="fas fa-edit"></i> Modifier
</a>
<a href="{{ url_for('additional_params_config.add', entity_type=entity_type, entity_slug=entity_slug) }}" 
   class="btn btn-outline-success">
    <i class="fas fa-cog"></i> Ajouter un paramètre
</a>
{% endmacro %}

{% macro info_card(title="Informations générales", icon="info-circle") %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title"><i class="fas fa-{{ icon }} me-2"></i>{{ title }}</h5>
        <dl class="row">
            {{ caller() }}
        </dl>
    </div>
</div>
{% endmacro %}

{% macro info_item(label, value, url=None) %}
<dt class="col-sm-4">{{ label }}</dt>
<dd class="col-sm-8">
    {% if url %}
        <a href="{{ url }}">{{ value }}</a>
    {% else %}
        {{ value }}
    {% endif %}
</dd>
{% endmacro %}

{% macro entity_list_section(title, items, template_partial, context={}, icon="list", empty_message="Aucun élément trouvé", add_url=None, add_text="Ajouter") %}
<div class="mb-5">
    {% if items and items|length > 0 %}
        {% with title=title, is_embedded=true, show_badge=true, show_add_button=true %}
            {% include template_partial with context %}
        {% endwith %}
    {% else %}
        <div class="alert alert-info">
            <i class="fas fa-info-circle me-2"></i>{{ empty_message }}
            {% if add_url %}
            <a href="{{ add_url }}" class="alert-link">{{ add_text }}</a>
            {% endif %}
        </div>
    {% endif %}
</div>
{% endmacro %}

app/templates/macros/_form.html
{# /templates/macros/_form.html #}

{% macro text_field(name, label, value="", required=false, placeholder="", help_text="", error=None, pattern=None, type="text", attributes="") %}
<div class="mb-3">
    <label for="{{ name }}" class="form-label">{{ label }}</label>
    <input type="{{ type }}"
           class="form-control {% if error %}is-invalid{% endif %}" 
           id="{{ name }}" 
           name="{{ name }}" 
           value="{{ value }}"
           {% if required %}required{% endif %}
           {% if placeholder %}placeholder="{{ placeholder }}"{% endif %}
           {% if pattern %}pattern="{{ pattern }}" title="{{ help_text }}"{% endif %}
           {{ attributes|safe }}>
    {% if error %}
    <div class="invalid-feedback">{{ error }}</div>
    {% elif help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro select_field(name, label, options, option_value, option_text, selected=None, required=false, help_text="", error=None, attributes="", multiple=false, add_button=None) %}
<div class="mb-3">
    <label for="{{ name }}" class="form-label">{{ label }}</label>
    <div class="input-group">
        <select class="form-select{% if error %} is-invalid{% endif %}" 
                id="{{ name }}" 
                name="{{ name }}{% if multiple %}[]{% endif %}" 
                {% if required %}required{% endif %} 
                {% if multiple %}multiple{% endif %}
                {{ attributes|safe }}>
            {% if not multiple %}
            <option value="" {% if not selected %}selected{% endif %} disabled>Choisir un {{ label|lower }}</option>
            {% endif %}
            {% for option in options %}
            <option value="{{ option[option_value] }}" 
                    {% if selected is not none and ((multiple and option[option_value] in selected) or (not multiple and selected|string == option[option_value]|string)) %}selected{% endif %}>
                {{ option[option_text] }}
            </option>
            {% endfor %}
        </select>
        {% if add_button %}
        <a href="{{ add_button.url }}" class="btn btn-secondary">
            {{ add_button.text }}
        </a>
        {% endif %}
    </div>
    {% if error %}
    <div class="invalid-feedback">{{ error }}</div>
    {% endif %}
    {% if help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro textarea_field(name, label, value="", rows=3, required=false, placeholder="", help_text="", error=None, attributes="") %}
<div class="mb-3">
    <label for="{{ name }}" class="form-label">{{ label }}</label>
    <textarea class="form-control {% if error %}is-invalid{% endif %}" 
              id="{{ name }}" 
              name="{{ name }}" 
              rows="{{ rows }}"
              {% if required %}required{% endif %}
              {% if placeholder %}placeholder="{{ placeholder }}"{% endif %}
              {{ attributes|safe }}>{{ value }}</textarea>
    {% if error %}
    <div class="invalid-feedback">{{ error }}</div>
    {% elif help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro checkbox_field(name, label, checked=false, help_text="", error=None, attributes="") %}
<div class="mb-3 form-check">
    <input type="checkbox" 
           class="form-check-input {% if error %}is-invalid{% endif %}" 
           id="{{ name }}" 
           name="{{ name }}"
           {% if checked %}checked{% endif %}
           {{ attributes|safe }}>
    <label class="form-check-label" for="{{ name }}">{{ label }}</label>
    {% if error %}
    <div class="invalid-feedback">{{ error }}</div>
    {% elif help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro radio_field(name, label, options, selected=None, required=false, help_text="", error=None, inline=false) %}
<div class="mb-3">
    <label class="form-label d-block">{{ label }}</label>
    {% for option in options %}
    <div class="form-check {% if inline %}form-check-inline{% endif %}">
        <input class="form-check-input {% if error %}is-invalid{% endif %}" 
               type="radio" 
               name="{{ name }}" 
               id="{{ name }}_{{ loop.index }}" 
               value="{{ option.value }}"
               {% if selected == option.value %}checked{% endif %}
               {% if required %}required{% endif %}>
        <label class="form-check-label" for="{{ name }}_{{ loop.index }}">
            {{ option.text }}
        </label>
    </div>
    {% endfor %}
    {% if error %}
    <div class="invalid-feedback d-block">{{ error }}</div>
    {% elif help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro file_field(name, label, required=false, accept=None, help_text="", error=None, multiple=false) %}
<div class="mb-3">
    <label for="{{ name }}" class="form-label">{{ label }}</label>
    <input type="file" 
           class="form-control {% if error %}is-invalid{% endif %}" 
           id="{{ name }}" 
           name="{{ name }}{% if multiple %}[]{% endif %}"
           {% if required %}required{% endif %}
           {% if accept %}accept="{{ accept }}"{% endif %}
           {% if multiple %}multiple{% endif %}>
    {% if error %}
    <div class="invalid-feedback">{{ error }}</div>
    {% elif help_text %}
    <div class="form-text">{{ help_text }}</div>
    {% endif %}
</div>
{% endmacro %}

{% macro submit_button(text="Enregistrer", icon="save", button_class="btn-primary", name="submit", value="1") %}
<button type="submit" class="btn {{ button_class }}" name="{{ name }}" value="{{ value }}">
    <i class="fas fa-{{ icon }} me-2"></i>{{ text }}
</button>
{% endmacro %}

{% macro cancel_button(url, text="Annuler", icon="times") %}
<a href="{{ url }}" class="btn btn-secondary">
    <i class="fas fa-{{ icon }} me-2"></i>{{ text }}
</a>
{% endmacro %}

app/templates/macros/_layout.html
{# /templates/macros/_layout.html #}

{% macro spaced_section(template_path, options={}, spacing_class="mb-5") %}
<div class="{{ spacing_class }}">
    {% include template_path with context %}
</div>
{% endmacro %}

{% macro param_card(param, entity_type, entity_slug, is_configured) %}
<div class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">{{ param.name }}</h5>
        <span class="badge bg-{{ 'success' if is_configured else 'warning' }}">
            {{ 'Configuré' if is_configured else 'À configurer' }}
        </span>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <p class="mb-1"><strong>Type :</strong> {{ param.type_display }}</p>
                <p class="mb-1"><strong>Valeur actuelle :</strong> {{ param.value|default('Non défini', true) }}</p>
            </div>
            <div class="col-md-6 text-end">
                {% if is_configured %}
                    <a href="{{ url_for('additional_params.edit', param_id=param.id) }}" 
                       class="btn btn-sm btn-outline-primary">
                        <i class="fas fa-edit"></i> Modifier
                    </a>
                {% else %}
                    <a href="{{ url_for('additional_params_config.add', entity_type=entity_type, entity_slug=entity_slug) }}?param_id={{ param.id }}" 
                       class="btn btn-sm btn-success">
                        <i class="fas fa-plus"></i> Ajouter
                    </a>
                {% endif %}
            </div>
        </div>
        {% if param.description %}
        <div class="mt-2">
            <p class="text-muted mb-0"><small>{{ param.description }}</small></p>
        </div>
        {% endif %}
    </div>
</div>
{% endmacro %}

app/templates/macros/_statistics.html
{# /templates/macros/_statistics.html #}

{% macro stats_cards(stats_items) %}
<div class="row mb-4">
    {% for item in stats_items %}
    <div class="col-md-4 mb-3">
        <div class="card border-{{ item.color|default('primary') }} h-100 shadow-sm">
            <div class="card-body text-center">
                <h5 class="card-title text-{{ item.color|default('primary') }} mb-3">
                    <i class="fas fa-{{ item.icon|default('chart-bar') }} me-2"></i>{{ item.title }}
                </h5>
                <div class="display-4 fw-bold text-muted">
                    {{ item.value }}
                </div>
                <small class="text-muted">{{ item.subtitle|default('') }}</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endmacro %}

{% macro stats_card(title="Statistiques", icon="chart-bar") %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title"><i class="fas fa-{{ icon }} me-2"></i>{{ title }}</h5>
        <dl class="row">
            {{ caller() }}
        </dl>
    </div>
</div>
{% endmacro %}

{% macro stats_item(label, value) %}
<dt class="col-sm-6">{{ label }}</dt>
<dd class="col-sm-6">{{ value }}</dd>
{% endmacro %}

{% macro indicateurs(items, title, color='primary') %}
<div class="col-md-4 mb-3">
    <div class="card border-{{ color }} h-100 shadow-sm">
        <div class="card-body text-center">
            <h5 class="card-title text-{{ color }} mb-3">
                <i class="fas fa-robot me-2"></i>{{ title }}
            </h5>
            <div class="display-4 fw-bold text-muted">
                {{ items|length }}
            </div>
            <small class="text-muted">dans le système</small>
        </div>
    </div>
</div>
{% endmacro %}